Repository cn-liontao/StandUp, pull requests merged in 2024-08, with the labels that each got.

#6 feat(ci): add ci release and test action
  .github/workflows/release.yaml
  .github/workflows/rust-test.yaml
  .github/workflows/version.yaml
  .github/workflows/web-test.yaml
Labels: enhancement, ci

#9 feat(tooltip): hover view block then toggle tooltip
  src/components/calendar/quarter-view.svelte
  src/components/tooltip/index.svelte
  src/lib/record-calc.ts
  src/routes/+page.svelte
  src/store/calendar.ts
Labels: enhancement

#7 fix(settings): sync settings along with window
  src-tauri/src/bridge/mod.rs
  src-tauri/src/main.rs
  src-tauri/src/ui/mod.rs
  src-tauri/src/ui/service.rs
  src-tauri/tauri.conf.json
Labels: bug

#14 fix(ci): specify pnpm version
  .github/workflows/vitepress.yml
Labels: ci

#15 fix(docs): set vitepress base to `/StandUp/`
  docs/.vitepress/config.ts
Labels: documentation
